// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkiupbzdobltnmpkacsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraXVwYnpkb2JsdG5tcGthY3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODY1MTAsImV4cCI6MjA2NDc2MjUxMH0.SJ4J88h1sVYLYgegrKRi4i-mwW57zryHv9d1w27NHIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);